# Generated by Django 6.0.3 on 2026-03-22 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('corrected_text', models.TextField(blank=True)),
                ('errors_found', models.JSONField(default=list)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
