# Generated by Django 6.0.3 on 2026-03-22 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('errors_detected', models.JSONField(blank=True, default=list)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('tense', 'Verb Tense'), ('article', 'Articles (a/an/the)'), ('preposition', 'Prepositions'), ('subject_verb', 'Subject-Verb Agreement'), ('spelling', 'Spelling'), ('punctuation', 'Punctuation'), ('word_order', 'Word Order'), ('vocabulary', 'Vocabulary'), ('other', 'Other')], max_length=20)),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('last_occurred', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weaknesses',
                'ordering': ['-frequency'],
                'unique_together': {('user', 'error_type')},
            },
        ),
    ]
